name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
      
jobs:
  cargo:
    name: Cargo test, clippy and doc
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: beta
          components: clippy, rustfmt
      
      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo test
        run: cargo test
      
      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Cargo clippy
        run: cargo clippy --all-features --message-format=json -- -D warnings > clippy_result.json
        continue-on-error: true
      
      - name: Install clippy-sarif sarif-fmt (require cargo)
        run: |
          cargo install clippy-sarif sarif-fmt
          cat clippy_result.json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true